<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $data = [
            ['name' => 'Atiquizaya', 'mun' => 1],
            ['name' => 'El Refugio', 'mun' => 1],
            ['name' => 'San Lorenzo', 'mun' => 1],
            ['name' => 'Ahuachapán', 'mun' => 2],
            ['name' => 'Apaneca', 'mun' => 2],
            ['name' => 'Concepción de Ataco', 'mun' => 2],
            ['name' => 'Tacuba', 'mun' => 2],
            ['name' => 'Guaymango', 'mun' => 3],
            ['name' => 'Jujutla', 'mun' => 3],
            ['name' => 'San Francisco Menendez', 'mun' => 3],
            ['name' => 'San Pedro Puxtla', 'mun' => 3],
            ['name' => 'Sensuntepeque', 'mun' => 4],
            ['name' => 'Victoria', 'mun' => 4],
            ['name' => 'Dolores', 'mun' => 4],
            ['name' => 'Guacotecti', 'mun' => 4],
            ['name' => 'San Isidro', 'mun' => 4],
            ['name' => 'Ilobasco', 'mun' => 5],
            ['name' => 'Tejutepeque', 'mun' => 5],
            ['name' => 'Jutiapa', 'mun' => 5],
            ['name' => 'Cinquera', 'mun' => 5],
            ['name' => 'La Palma', 'mun' => 6],
            ['name' => 'Citalá', 'mun' => 6],
            ['name' => 'San Ignacio', 'mun' => 6],
            ['name' => 'Nueva Concepción', 'mun' => 7],
            ['name' => 'Tejutla', 'mun' => 7],
            ['name' => 'La Reina', 'mun' => 7],
            ['name' => 'Agua Caliente', 'mun' => 7],
            ['name' => 'Dulce Nombre de María', 'mun' => 7],
            ['name' => 'El Paraíso', 'mun' => 7],
            ['name' => 'San Francisco Morazán', 'mun' => 7],
            ['name' => 'San Rafael', 'mun' => 7],
            ['name' => 'Santa Rita', 'mun' => 7],
            ['name' => 'San Fernando', 'mun' => 7],
            ['name' => 'Chalatenango', 'mun' => 8],
            ['name' => 'Arcatao', 'mun' => 8],
            ['name' => 'Azacualpa', 'mun' => 8],
            ['name' => 'Comalapa', 'mun' => 8],
            ['name' => 'Concepción Quezaltepeque', 'mun' => 8],
            ['name' => 'El Carrizal', 'mun' => 8],
            ['name' => 'La Laguna', 'mun' => 8],
            ['name' => 'Las Vueltas', 'mun' => 8],
            ['name' => 'Nombre de Jesús', 'mun' => 8],
            ['name' => 'Nueva Trinidad', 'mun' => 8],
            ['name' => 'Ojos de Agua', 'mun' => 8],
            ['name' => 'Potonico', 'mun' => 8],
            ['name' => 'San Antonio de La Cruz', 'mun' => 8],
            ['name' => 'San Antonio Los Ranchos', 'mun' => 8],
            ['name' => 'San Francisco Lempa', 'mun' => 8],
            ['name' => 'San Isidro Labrador', 'mun' => 8],
            ['name' => 'San José Cancasque', 'mun' => 8],
            ['name' => 'San Miguel de Mercedes', 'mun' => 8],
            ['name' => 'San José Las Flores', 'mun' => 8],
            ['name' => 'San Luis del Carmen', 'mun' => 8],
            ['name' => 'Suchitoto', 'mun' => 9],
            ['name' => 'San José Guayabal', 'mun' => 9],
            ['name' => 'Oratorio de Concepción', 'mun' => 9],
            ['name' => 'San Bartolomé Perulapán', 'mun' => 9],
            ['name' => 'San Pedro Perulapán', 'mun' => 9],
            ['name' => 'Cojutepeque', 'mun' => 10],
            ['name' => 'San Rafael Cedros', 'mun' => 10],
            ['name' => 'Candelaria', 'mun' => 10],
            ['name' => 'Monte San Juan', 'mun' => 10],
            ['name' => 'El Carmen', 'mun' => 10],
            ['name' => 'San Cristóbal', 'mun' => 10],
            ['name' => 'Santa Cruz Michapa', 'mun' => 10],
            ['name' => 'San Ramón', 'mun' => 10],
            ['name' => 'El Rosario', 'mun' => 10],
            ['name' => 'Santa Cruz Analquito', 'mun' => 10],
            ['name' => 'Tenancingo', 'mun' => 10],
            ['name' => 'Quezaltepeque', 'mun' => 11],
            ['name' => 'San Matías', 'mun' => 11],
            ['name' => 'San Pablo Tacachico', 'mun' => 11],
            ['name' => 'San Juan Opico', 'mun' => 12],
            ['name' => 'Ciudad Arce', 'mun' => 12],
            ['name' => 'Lourdes colón', 'mun' => 13],
            ['name' => 'Jayaque', 'mun' => 13],
            ['name' => 'Sacacoyo', 'mun' => 13],
            ['name' => 'Tepecoyo', 'mun' => 13],
            ['name' => 'Talnique', 'mun' => 13],
            ['name' => 'Antiguo Cuscatlán', 'mun' => 14],
            ['name' => 'Huizúcar', 'mun' => 14],
            ['name' => 'Nuevo Cuscatlán', 'mun' => 14],
            ['name' => 'San José Villanueva', 'mun' => 14],
            ['name' => 'Zaragoza', 'mun' => 14],
            ['name' => 'Chiltuipán', 'mun' => 15],
            ['name' => 'Jicalapa', 'mun' => 15],
            ['name' => 'La Libertad', 'mun' => 15],
            ['name' => 'Tamanique', 'mun' => 15],
            ['name' => 'Teotepeque', 'mun' => 15],
            ['name' => 'Comasagua', 'mun' => 16],
            ['name' => 'Santa Tecla', 'mun' => 16],
            ['name' => 'Cuyultitán', 'mun' => 17],
            ['name' => 'Olocuilta', 'mun' => 17],
            ['name' => 'San Juan Talpa', 'mun' => 17],
            ['name' => 'San Luis Talpa', 'mun' => 17],
            ['name' => 'San Pedro Masahuat', 'mun' => 17],
            ['name' => 'Tapalhuaca', 'mun' => 17],
            ['name' => 'San Francisco Chinameca', 'mun' => 17],
            ['name' => 'El Rosario', 'mun' => 18],
            ['name' => 'Jerusalén', 'mun' => 18],
            ['name' => 'Mercedes La Ceiba', 'mun' => 18],
            ['name' => 'Paraíso de Osorio', 'mun' => 18],
            ['name' => 'San Antonio Masahuat', 'mun' => 18],
            ['name' => 'San Emigdio', 'mun' => 18],
            ['name' => 'San Juan Tepezontes', 'mun' => 18],
            ['name' => 'San Luis La Herradura', 'mun' => 18],
            ['name' => 'San Miguel Tepezontes', 'mun' => 18],
            ['name' => 'San Pedro Nonualco', 'mun' => 18],
            ['name' => 'Santa María Ostuma', 'mun' => 18],
            ['name' => 'Santiago Nonualco', 'mun' => 18],
            ['name' => 'San Juan Nonualco', 'mun' => 19],
            ['name' => 'San Rafael Obrajuelo', 'mun' => 19],
            ['name' => 'Zacatecoluca', 'mun' => 19],
            ['name' => 'Anamorós', 'mun' => 20],
            ['name' => 'Bolivar', 'mun' => 20],
            ['name' => 'Concepción de Oriente', 'mun' => 20],
            ['name' => 'El Sauce', 'mun' => 20],
            ['name' => 'Lislique', 'mun' => 20],
            ['name' => 'Nueva Esparta', 'mun' => 20],
            ['name' => 'Pasaquina', 'mun' => 20],
            ['name' => 'Polorós', 'mun' => 20],
            ['name' => 'San José La Fuente', 'mun' => 20],
            ['name' => 'Santa Rosa de Lima', 'mun' => 20],
            ['name' => 'Conchagua', 'mun' => 21],
            ['name' => 'El Carmen', 'mun' => 21],
            ['name' => 'Intipucá', 'mun' => 21],
            ['name' => 'La Unión', 'mun' => 21],
            ['name' => 'Meanguera del Golfo', 'mun' => 21],
            ['name' => 'San Alejo', 'mun' => 21],
            ['name' => 'Yayantique', 'mun' => 21],
            ['name' => 'Yucuaiquín', 'mun' => 21],
            ['name' => 'Arambala', 'mun' => 22],
            ['name' => 'Cacaopera', 'mun' => 22],
            ['name' => 'Corinto', 'mun' => 22],
            ['name' => 'El Rosario', 'mun' => 22],
            ['name' => 'Joateca', 'mun' => 22],
            ['name' => 'Jocoaitique', 'mun' => 22],
            ['name' => 'Meanguera', 'mun' => 22],
            ['name' => 'Perquín', 'mun' => 22],
            ['name' => 'San Fernando', 'mun' => 22],
            ['name' => 'San Isidro', 'mun' => 22],
            ['name' => 'Torola', 'mun' => 22],
            ['name' => 'Chilanga', 'mun' => 23],
            ['name' => 'Delicias de Concepción', 'mun' => 23],
            ['name' => 'El Divisadero', 'mun' => 23],
            ['name' => 'Gualococti', 'mun' => 23],
            ['name' => 'Guatajiagua', 'mun' => 23],
            ['name' => 'Jocoro', 'mun' => 23],
            ['name' => 'Lolotiquillo', 'mun' => 23],
            ['name' => 'Osicala', 'mun' => 23],
            ['name' => 'San Carlos', 'mun' => 23],
            ['name' => 'San Francisco Gotera', 'mun' => 23],
            ['name' => 'San Simón', 'mun' => 23],
            ['name' => 'Sensembra', 'mun' => 23],
            ['name' => 'Sociedad', 'mun' => 23],
            ['name' => 'Yamabal', 'mun' => 23],
            ['name' => 'Yoloaiquín', 'mun' => 23],
            ['name' => 'Ciudad Barrios', 'mun' => 24],
            ['name' => 'Sesori', 'mun' => 24],
            ['name' => 'Nuevo Edén de San Juan', 'mun' => 24],
            ['name' => 'San Gerardo', 'mun' => 24],
            ['name' => 'San Luis de La Reina', 'mun' => 24],
            ['name' => 'Carolina', 'mun' => 24],
            ['name' => 'San Antonio del Mosco', 'mun' => 24],
            ['name' => 'Chapeltique', 'mun' => 24],
            ['name' => 'San Miguel', 'mun' => 25],
            ['name' => 'Comacarán', 'mun' => 25],
            ['name' => 'Uluazapa', 'mun' => 25],
            ['name' => 'Moncagua', 'mun' => 25],
            ['name' => 'Quelepa', 'mun' => 25],
            ['name' => 'Chirilagua', 'mun' => 25],
            ['name' => 'Chinameca', 'mun' => 26],
            ['name' => 'Nueva Guadalupe', 'mun' => 26],
            ['name' => 'Lolotique', 'mun' => 26],
            ['name' => 'San Jorge', 'mun' => 26],
            ['name' => 'San Rafael Oriente', 'mun' => 26],
            ['name' => 'El Tránsito', 'mun' => 26],
            ['name' => 'Aguilares', 'mun' => 27],
            ['name' => 'El Paisnal', 'mun' => 27],
            ['name' => 'Guazapa', 'mun' => 27],
            ['name' => 'Apopa', 'mun' => 28],
            ['name' => 'Nejapa', 'mun' => 28],
            ['name' => 'Ilopango', 'mun' => 29],
            ['name' => 'San Martín', 'mun' => 29],
            ['name' => 'Soyapango', 'mun' => 29],
            ['name' => 'Tonacatepeque', 'mun' => 29],
            ['name' => 'Ayutuxtepeque', 'mun' => 30],
            ['name' => 'Mejicanos', 'mun' => 30],
            ['name' => 'San Salvador', 'mun' => 30],
            ['name' => 'Cuscatancingo', 'mun' => 30],
            ['name' => 'Ciudad Delgado', 'mun' => 30],
            ['name' => 'Panchimalco', 'mun' => 31],
            ['name' => 'Rosario de Mora', 'mun' => 31],
            ['name' => 'San Marcos', 'mun' => 31],
            ['name' => 'Santo Tomás', 'mun' => 31],
            ['name' => 'Santiago Texacuangos', 'mun' => 31],
            ['name' => 'Apastepeque', 'mun' => 32],
            ['name' => 'Santa Clara', 'mun' => 32],
            ['name' => 'San Ildefonso', 'mun' => 32],
            ['name' => 'San Esteban Catarina', 'mun' => 32],
            ['name' => 'San Sebastián', 'mun' => 32],
            ['name' => 'San Lorenzo', 'mun' => 32],
            ['name' => 'Santo Domingo', 'mun' => 32],
            ['name' => 'San Vicente', 'mun' => 33],
            ['name' => 'Guadalupe', 'mun' => 33],
            ['name' => 'Verapaz', 'mun' => 33],
            ['name' => 'Tepetitán', 'mun' => 33],
            ['name' => 'Tecoluca', 'mun' => 33],
            ['name' => 'San Cayetano Istepeque', 'mun' => 33],
            ['name' => 'Masahuat', 'mun' => 34],
            ['name' => 'Metapán', 'mun' => 34],
            ['name' => 'Santa Rosa Guachipilín', 'mun' => 34],
            ['name' => 'Texistepeque', 'mun' => 34],
            ['name' => 'Santa Ana', 'mun' => 35],
            ['name' => 'Coatepeque', 'mun' => 36],
            ['name' => 'El Congo', 'mun' => 36],
            ['name' => 'Candelaria de la Frontera', 'mun' => 37],
            ['name' => 'Chalchuapa', 'mun' => 37],
            ['name' => 'El Porvenir', 'mun' => 37],
            ['name' => 'San Antonio Pajonal', 'mun' => 37],
            ['name' => 'San Sebastián Salitrillo', 'mun' => 37],
            ['name' => 'Santiago de La Frontera', 'mun' => 37],
            ['name' => 'Juayúa', 'mun' => 38],
            ['name' => 'Nahuizalco', 'mun' => 38],
            ['name' => 'Salcoatitán', 'mun' => 38],
            ['name' => 'Santa Catarina Masahuat', 'mun' => 38],
            ['name' => 'Sonsonate', 'mun' => 39],
            ['name' => 'Sonzacate', 'mun' => 39],
            ['name' => 'Nahulingo', 'mun' => 39],
            ['name' => 'San Antonio del Monte', 'mun' => 39],
            ['name' => 'Santo Domingo de Guzmán', 'mun' => 39],
            ['name' => 'Izalco', 'mun' => 40],
            ['name' => 'Armenia', 'mun' => 40],
            ['name' => 'Caluco', 'mun' => 40],
            ['name' => 'San Julián', 'mun' => 40],
            ['name' => 'Cuisnahuat', 'mun' => 40],
            ['name' => 'Santa Isabel Ishuatán', 'mun' => 40],
            ['name' => 'Acajutla', 'mun' => 41],
            ['name' => 'Santiago de María', 'mun' => 42],
            ['name' => 'Alegría', 'mun' => 42],
            ['name' => 'Berlín', 'mun' => 42],
            ['name' => 'Mercedes Umaña', 'mun' => 42],
            ['name' => 'Jucuapa', 'mun' => 42],
            ['name' => 'El Triunfo', 'mun' => 42],
            ['name' => 'Estanzuelas', 'mun' => 42],
            ['name' => 'San Buenaventura', 'mun' => 42],
            ['name' => 'Nueva Granada', 'mun' => 42],
            ['name' => 'Usulután', 'mun' => 43],
            ['name' => 'Jucuarán', 'mun' => 43],
            ['name' => 'San Dionisio', 'mun' => 43],
            ['name' => 'Concepción Batres', 'mun' => 43],
            ['name' => 'Santa María', 'mun' => 43],
            ['name' => 'Ozatlán', 'mun' => 43],
            ['name' => 'Tecapán', 'mun' => 43],
            ['name' => 'Santa Elena', 'mun' => 43],
            ['name' => 'California', 'mun' => 43],
            ['name' => 'Ereguayquín', 'mun' => 43],
            ['name' => 'Jiquilisco', 'mun' => 44],
            ['name' => 'Puerto El Triunfo', 'mun' => 44],
            ['name' => 'San Agustín', 'mun' => 44],
            ['name' => 'San Francisco Javier', 'mun' => 44],
        ];
        foreach ($data as $items) {
            District::create([
                'name' => $items['name'],
                'municipality_id' => $items['mun'],
            ]);
        }
    }
}
