<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\PaisModel;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrayData = array();
        array_push($arrayData,  array('nombre' => 'Afganistán', 'area' => '93'),
                                array('nombre' => 'Albania', 'area' => '355'),
                                array('nombre' => 'Alemania', 'area' => '49'),
                                array('nombre' => 'Andorra', 'area' => '376'),
                                array('nombre' => 'Angola', 'area' => '244'),
                                array('nombre' => 'Anguila', 'area' => '1 264'),
                                array('nombre' => 'Antártida', 'area' => '672'),
                                array('nombre' => 'Antigua y Barbuda', 'area' => '1 268'),
                                array('nombre' => 'Arabia Saudita', 'area' => '966'),
                                array('nombre' => 'Argelia', 'area' => '213'),
                                array('nombre' => 'Argentina', 'area' => '54'),
                                array('nombre' => 'Armenia', 'area' => '374'),
                                array('nombre' => 'Aruba', 'area' => '297'),
                                array('nombre' => 'Australia', 'area' => '61'),
                                array('nombre' => 'Austria', 'area' => '43'),
                                array('nombre' => 'Azerbaiyán', 'area' => '994'),
                                array('nombre' => 'Bélgica', 'area' => '32'),
                                array('nombre' => 'Bahamas', 'area' => '1 242'),
                                array('nombre' => 'Bahrein', 'area' => '973'),
                                array('nombre' => 'Bangladesh', 'area' => '880'),
                                array('nombre' => 'Barbados', 'area' => '1 246'),
                                array('nombre' => 'Belice', 'area' => '501'),
                                array('nombre' => 'Benín', 'area' => '229'),
                                array('nombre' => 'Bhután', 'area' => '975'),
                                array('nombre' => 'Bielorrusia', 'area' => '375'),
                                array('nombre' => 'Birmania', 'area' => '95'),
                                array('nombre' => 'Bolivia', 'area' => '591'),
                                array('nombre' => 'Bosnia y Herzegovina', 'area' => '387'),
                                array('nombre' => 'Botsuana', 'area' => '267'),
                                array('nombre' => 'Brasil', 'area' => '55'),
                                array('nombre' => 'Brunéi', 'area' => '673'),
                                array('nombre' => 'Bulgaria', 'area' => '359'),
                                array('nombre' => 'Burkina Faso', 'area' => '226'),
                                array('nombre' => 'Burundi', 'area' => '257'),
                                array('nombre' => 'Cabo Verde', 'area' => '238'),
                                array('nombre' => 'Camboya', 'area' => '855'),
                                array('nombre' => 'Camerún', 'area' => '237'),
                                array('nombre' => 'Canadá', 'area' => '1'),
                                array('nombre' => 'Chad', 'area' => '235'),
                                array('nombre' => 'Chile', 'area' => '56'),
                                array('nombre' => 'China', 'area' => '86'),
                                array('nombre' => 'Chipre', 'area' => '357'),
                                array('nombre' => 'Ciudad del Vaticano', 'area' => '39'),
                                array('nombre' => 'Colombia', 'area' => '57'),
                                array('nombre' => 'Comoras', 'area' => '269'),
                                array('nombre' => 'República del Congo', 'area' => '242'),
                                array('nombre' => 'República Democrática del Congo', 'area' => '243'),
                                array('nombre' => 'Corea del Norte', 'area' => '850'),
                                array('nombre' => 'Corea del Sur', 'area' => '82'),
                                array('nombre' => 'Costa de Marfil', 'area' => '225'),
                                array('nombre' => 'Costa Rica', 'area' => '506'),
                                array('nombre' => 'Croacia', 'area' => '385'),
                                array('nombre' => 'Cuba', 'area' => '53'),
                                array('nombre' => 'Curazao', 'area' => '5999'),
                                array('nombre' => 'Dinamarca', 'area' => '45'),
                                array('nombre' => 'Dominica', 'area' => '1 767'),
                                array('nombre' => 'Ecuador', 'area' => '593'),
                                array('nombre' => 'Egipto', 'area' => '20'),
                                array('nombre' => 'El Salvador', 'area' => '503'),
                                array('nombre' => 'Emiratos Árabes Unidos', 'area' => '971'),
                                array('nombre' => 'Eritrea', 'area' => '291'),
                                array('nombre' => 'Eslovaquia', 'area' => '421'),
                                array('nombre' => 'Eslovenia', 'area' => '386'),
                                array('nombre' => 'España', 'area' => '34'),
                                array('nombre' => 'Estados Unidos de América', 'area' => '1'),
                                array('nombre' => 'Estonia', 'area' => '372'),
                                array('nombre' => 'Etiopía', 'area' => '251'),
                                array('nombre' => 'Filipinas', 'area' => '63'),
                                array('nombre' => 'Finlandia', 'area' => '358'),
                                array('nombre' => 'Fiyi', 'area' => '679'),
                                array('nombre' => 'Francia', 'area' => '33'),
                                array('nombre' => 'Gabón', 'area' => '241'),
                                array('nombre' => 'Gambia', 'area' => '220'),
                                array('nombre' => 'Georgia', 'area' => '995'),
                                array('nombre' => 'Ghana', 'area' => '233'),
                                array('nombre' => 'Gibraltar', 'area' => '350'),
                                array('nombre' => 'Granada', 'area' => '1 473'),
                                array('nombre' => 'Grecia', 'area' => '30'),
                                array('nombre' => 'Groenlandia', 'area' => '299'),
                                array('nombre' => 'Guadalupe', 'area' => '590'),
                                array('nombre' => 'Guam', 'area' => '1 671'),
                                array('nombre' => 'Guatemala', 'area' => '502'),
                                array('nombre' => 'Guayana Francesa', 'area' => '594'),
                                array('nombre' => 'Guernsey', 'area' => '44'),
                                array('nombre' => 'Guinea', 'area' => '224'),
                                array('nombre' => 'Guinea Ecuatorial', 'area' => '240'),
                                array('nombre' => 'Guinea-Bissau', 'area' => '245'),
                                array('nombre' => 'Guyana', 'area' => '592'),
                                array('nombre' => 'Haití', 'area' => '509'),
                                array('nombre' => 'Honduras', 'area' => '504'),
                                array('nombre' => 'Hong kong', 'area' => '852'),
                                array('nombre' => 'Hungría', 'area' => '36'),
                                array('nombre' => 'India', 'area' => '91'),
                                array('nombre' => 'Indonesia', 'area' => '62'),
                                array('nombre' => 'Irán', 'area' => '98'),
                                array('nombre' => 'Irak', 'area' => '964'),
                                array('nombre' => 'Irlanda', 'area' => '353'),
                                array('nombre' => 'Isla Bouvet', 'area' => ''),
                                array('nombre' => 'Isla de Man', 'area' => '44'),
                                array('nombre' => 'Isla de Navidad', 'area' => '61'),
                                array('nombre' => 'Isla Norfolk', 'area' => '672'),
                                array('nombre' => 'Islandia', 'area' => '354'),
                                array('nombre' => 'Islas Bermudas', 'area' => '1 441'),
                                array('nombre' => 'Islas Caimán', 'area' => '1 345'),
                                array('nombre' => 'Islas Cocos (Keeling)', 'area' => '61'),
                                array('nombre' => 'Islas Cook', 'area' => '682'),
                                array('nombre' => 'Islas de Åland', 'area' => '358'),
                                array('nombre' => 'Islas Feroe', 'area' => '298'),
                                array('nombre' => 'Islas Georgias del Sur y Sandwich del Sur', 'area' => '500'),
                                array('nombre' => 'Islas Heard y McDonald', 'area' => ''),
                                array('nombre' => 'Islas Maldivas', 'area' => '960'),
                                array('nombre' => 'Islas Malvinas', 'area' => '500'),
                                array('nombre' => 'Islas Marianas del Norte', 'area' => '1 670'),
                                array('nombre' => 'Islas Marshall', 'area' => '692'),
                                array('nombre' => 'Islas Pitcairn', 'area' => '870'),
                                array('nombre' => 'Islas Salomón', 'area' => '677'),
                                array('nombre' => 'Islas Turcas y Caicos', 'area' => '1 649'),
                                array('nombre' => 'Islas Ultramarinas Menores de Estados Unidos', 'area' => '246'),
                                array('nombre' => 'Islas Vírgenes Británicas', 'area' => '1 284'),
                                array('nombre' => 'Islas Vírgenes de los Estados Unidos', 'area' => '1 340'),
                                array('nombre' => 'Israel', 'area' => '972'),
                                array('nombre' => 'Italia', 'area' => '39'),
                                array('nombre' => 'Jamaica', 'area' => '1 876'),
                                array('nombre' => 'Japón', 'area' => '81'),
                                array('nombre' => 'Jersey', 'area' => '44'),
                                array('nombre' => 'Jordania', 'area' => '962'),
                                array('nombre' => 'Kazajistán', 'area' => '7'),
                                array('nombre' => 'Kenia', 'area' => '254'),
                                array('nombre' => 'Kirguistán', 'area' => '996'),
                                array('nombre' => 'Kiribati', 'area' => '686'),
                                array('nombre' => 'Kuwait', 'area' => '965'),
                                array('nombre' => 'Líbano', 'area' => '961'),
                                array('nombre' => 'Laos', 'area' => '856'),
                                array('nombre' => 'Lesoto', 'area' => '266'),
                                array('nombre' => 'Letonia', 'area' => '371'),
                                array('nombre' => 'Liberia', 'area' => '231'),
                                array('nombre' => 'Libia', 'area' => '218'),
                                array('nombre' => 'Liechtenstein', 'area' => '423'),
                                array('nombre' => 'Lituania', 'area' => '370'),
                                array('nombre' => 'Luxemburgo', 'area' => '352'),
                                array('nombre' => 'México', 'area' => '52'),
                                array('nombre' => 'Mónaco', 'area' => '377'),
                                array('nombre' => 'Macao', 'area' => '853'),
                                array('nombre' => 'Macedônia', 'area' => '389'),
                                array('nombre' => 'Madagascar', 'area' => '261'),
                                array('nombre' => 'Malasia', 'area' => '60'),
                                array('nombre' => 'Malawi', 'area' => '265'),
                                array('nombre' => 'Mali', 'area' => '223'),
                                array('nombre' => 'Malta', 'area' => '356'),
                                array('nombre' => 'Marruecos', 'area' => '212'),
                                array('nombre' => 'Martinica', 'area' => '596'),
                                array('nombre' => 'Mauricio', 'area' => '230'),
                                array('nombre' => 'Mauritania', 'area' => '222'),
                                array('nombre' => 'Mayotte', 'area' => '262'),
                                array('nombre' => 'Micronesia', 'area' => '691'),
                                array('nombre' => 'Moldavia', 'area' => '373'),
                                array('nombre' => 'Mongolia', 'area' => '976'),
                                array('nombre' => 'Montenegro', 'area' => '382'),
                                array('nombre' => 'Montserrat', 'area' => '1 664'),
                                array('nombre' => 'Mozambique', 'area' => '258'),
                                array('nombre' => 'Namibia', 'area' => '264'),
                                array('nombre' => 'Nauru', 'area' => '674'),
                                array('nombre' => 'Nepal', 'area' => '977'),
                                array('nombre' => 'Nicaragua', 'area' => '505'),
                                array('nombre' => 'Niger', 'area' => '227'),
                                array('nombre' => 'Nigeria', 'area' => '234'),
                                array('nombre' => 'Niue', 'area' => '683'),
                                array('nombre' => 'Noruega', 'area' => '47'),
                                array('nombre' => 'Nueva Caledonia', 'area' => '687'),
                                array('nombre' => 'Nueva Zelanda', 'area' => '64'),
                                array('nombre' => 'Omán', 'area' => '968'),
                                array('nombre' => 'Países Bajos', 'area' => '31'),
                                array('nombre' => 'Pakistán', 'area' => '92'),
                                array('nombre' => 'Palau', 'area' => '680'),
                                array('nombre' => 'Palestina', 'area' => '970'),
                                array('nombre' => 'Panamá', 'area' => '507'),
                                array('nombre' => 'Papúa Nueva Guinea', 'area' => '675'),
                                array('nombre' => 'Paraguay', 'area' => '595'),
                                array('nombre' => 'Perú', 'area' => '51'),
                                array('nombre' => 'Polinesia Francesa', 'area' => '689'),
                                array('nombre' => 'Polonia', 'area' => '48'),
                                array('nombre' => 'Portugal', 'area' => '351'),
                                array('nombre' => 'Puerto Rico', 'area' => '1'),
                                array('nombre' => 'Qatar', 'area' => '974'),
                                array('nombre' => 'Reino Unido', 'area' => '44'),
                                array('nombre' => 'República Centroafricana', 'area' => '236'),
                                array('nombre' => 'República Checa', 'area' => '420'),
                                array('nombre' => 'República Dominicana', 'area' => '1 809'),
                                array('nombre' => 'República de Sudán del Sur', 'area' => '211'),
                                array('nombre' => 'Reunión', 'area' => '262'),
                                array('nombre' => 'Ruanda', 'area' => '250'),
                                array('nombre' => 'Rumanía', 'area' => '40'),
                                array('nombre' => 'Rusia', 'area' => '7'),
                                array('nombre' => 'Sahara Occidental', 'area' => '212'),
                                array('nombre' => 'Samoa', 'area' => '685'),
                                array('nombre' => 'Samoa Americana', 'area' => '1 684'),
                                array('nombre' => 'San Bartolomé', 'area' => '590'),
                                array('nombre' => 'San Cristóbal y Nieves', 'area' => '1 869'),
                                array('nombre' => 'San Marino', 'area' => '378'),
                                array('nombre' => 'San Martín (Francia)', 'area' => '1 599'),
                                array('nombre' => 'San Pedro y Miquelón', 'area' => '508'),
                                array('nombre' => 'San Vicente y las Granadinas', 'area' => '1 784'),
                                array('nombre' => 'Santa Elena', 'area' => '290'),
                                array('nombre' => 'Santa Lucía', 'area' => '1 758'),
                                array('nombre' => 'Santo Tomé y Príncipe', 'area' => '239'),
                                array('nombre' => 'Senegal', 'area' => '221'),
                                array('nombre' => 'Serbia', 'area' => '381'),
                                array('nombre' => 'Seychelles', 'area' => '248'),
                                array('nombre' => 'Sierra Leona', 'area' => '232'),
                                array('nombre' => 'Singapur', 'area' => '65'),
                                array('nombre' => 'Sint Maarten', 'area' => '1 721'),
                                array('nombre' => 'Siria', 'area' => '963'),
                                array('nombre' => 'Somalia', 'area' => '252'),
                                array('nombre' => 'Sri lanka', 'area' => '94'),
                                array('nombre' => 'Sudáfrica', 'area' => '27'),
                                array('nombre' => 'Sudán', 'area' => '249'),
                                array('nombre' => 'Suecia', 'area' => '46'),
                                array('nombre' => 'Suiza', 'area' => '41'),
                                array('nombre' => 'Surinám', 'area' => '597'),
                                array('nombre' => 'Svalbard y Jan Mayen', 'area' => '47'),
                                array('nombre' => 'Swazilandia', 'area' => '268'),
                                array('nombre' => 'Tayikistán', 'area' => '992'),
                                array('nombre' => 'Tailandia', 'area' => '66'),
                                array('nombre' => 'Taiwán', 'area' => '886'),
                                array('nombre' => 'Tanzania', 'area' => '255'),
                                array('nombre' => 'Territorio Británico del Océano Índico', 'area' => '246'),
                                array('nombre' => 'Territorios Australes y Antárticas Franceses', 'area' => ''),
                                array('nombre' => 'Timor Oriental', 'area' => '670'),
                                array('nombre' => 'Togo', 'area' => '228'),
                                array('nombre' => 'Tokelau', 'area' => '690'),
                                array('nombre' => 'Tonga', 'area' => '676'),
                                array('nombre' => 'Trinidad y Tobago', 'area' => '1 868'),
                                array('nombre' => 'Tunez', 'area' => '216'),
                                array('nombre' => 'Turkmenistán', 'area' => '993'),
                                array('nombre' => 'Turquía', 'area' => '90'),
                                array('nombre' => 'Tuvalu', 'area' => '688'),
                                array('nombre' => 'Ucrania', 'area' => '380'),
                                array('nombre' => 'Uganda', 'area' => '256'),
                                array('nombre' => 'Uruguay', 'area' => '598'),
                                array('nombre' => 'Uzbekistán', 'area' => '998'),
                                array('nombre' => 'Vanuatu', 'area' => '678'),
                                array('nombre' => 'Venezuela', 'area' => '58'),
                                array('nombre' => 'Vietnam', 'area' => '84'),
                                array('nombre' => 'Wallis y Futuna', 'area' => '681'),
                                array('nombre' => 'Yemen', 'area' => '967'),
                                array('nombre' => 'Yibuti', 'area' => '253'),
                                array('nombre' => 'Zambia', 'area' => '260'),
                                array('nombre' => 'Zimbabue', 'area' => '263'),
        );
        foreach ($arrayData as $key => $value) {
            PaisModel::create([
                'nombre' => $value['nombre'],
                'area'   => $value['area'],
            ]);
        }
    }
}
