<?php

namespace Database\Seeders;

use App\Models\PaisModel;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrayData = [];
        array_push($arrayData, ['nombre' => 'Afganistán', 'area' => '93'],
            ['nombre' => 'Albania', 'area' => '355'],
            ['nombre' => 'Alemania', 'area' => '49'],
            ['nombre' => 'Andorra', 'area' => '376'],
            ['nombre' => 'Angola', 'area' => '244'],
            ['nombre' => 'Anguila', 'area' => '1 264'],
            ['nombre' => 'Antártida', 'area' => '672'],
            ['nombre' => 'Antigua y Barbuda', 'area' => '1 268'],
            ['nombre' => 'Arabia Saudita', 'area' => '966'],
            ['nombre' => 'Argelia', 'area' => '213'],
            ['nombre' => 'Argentina', 'area' => '54'],
            ['nombre' => 'Armenia', 'area' => '374'],
            ['nombre' => 'Aruba', 'area' => '297'],
            ['nombre' => 'Australia', 'area' => '61'],
            ['nombre' => 'Austria', 'area' => '43'],
            ['nombre' => 'Azerbaiyán', 'area' => '994'],
            ['nombre' => 'Bélgica', 'area' => '32'],
            ['nombre' => 'Bahamas', 'area' => '1 242'],
            ['nombre' => 'Bahrein', 'area' => '973'],
            ['nombre' => 'Bangladesh', 'area' => '880'],
            ['nombre' => 'Barbados', 'area' => '1 246'],
            ['nombre' => 'Belice', 'area' => '501'],
            ['nombre' => 'Benín', 'area' => '229'],
            ['nombre' => 'Bhután', 'area' => '975'],
            ['nombre' => 'Bielorrusia', 'area' => '375'],
            ['nombre' => 'Birmania', 'area' => '95'],
            ['nombre' => 'Bolivia', 'area' => '591'],
            ['nombre' => 'Bosnia y Herzegovina', 'area' => '387'],
            ['nombre' => 'Botsuana', 'area' => '267'],
            ['nombre' => 'Brasil', 'area' => '55'],
            ['nombre' => 'Brunéi', 'area' => '673'],
            ['nombre' => 'Bulgaria', 'area' => '359'],
            ['nombre' => 'Burkina Faso', 'area' => '226'],
            ['nombre' => 'Burundi', 'area' => '257'],
            ['nombre' => 'Cabo Verde', 'area' => '238'],
            ['nombre' => 'Camboya', 'area' => '855'],
            ['nombre' => 'Camerún', 'area' => '237'],
            ['nombre' => 'Canadá', 'area' => '1'],
            ['nombre' => 'Chad', 'area' => '235'],
            ['nombre' => 'Chile', 'area' => '56'],
            ['nombre' => 'China', 'area' => '86'],
            ['nombre' => 'Chipre', 'area' => '357'],
            ['nombre' => 'Ciudad del Vaticano', 'area' => '39'],
            ['nombre' => 'Colombia', 'area' => '57'],
            ['nombre' => 'Comoras', 'area' => '269'],
            ['nombre' => 'República del Congo', 'area' => '242'],
            ['nombre' => 'República Democrática del Congo', 'area' => '243'],
            ['nombre' => 'Corea del Norte', 'area' => '850'],
            ['nombre' => 'Corea del Sur', 'area' => '82'],
            ['nombre' => 'Costa de Marfil', 'area' => '225'],
            ['nombre' => 'Costa Rica', 'area' => '506'],
            ['nombre' => 'Croacia', 'area' => '385'],
            ['nombre' => 'Cuba', 'area' => '53'],
            ['nombre' => 'Curazao', 'area' => '5999'],
            ['nombre' => 'Dinamarca', 'area' => '45'],
            ['nombre' => 'Dominica', 'area' => '1 767'],
            ['nombre' => 'Ecuador', 'area' => '593'],
            ['nombre' => 'Egipto', 'area' => '20'],
            ['nombre' => 'El Salvador', 'area' => '503'],
            ['nombre' => 'Emiratos Árabes Unidos', 'area' => '971'],
            ['nombre' => 'Eritrea', 'area' => '291'],
            ['nombre' => 'Eslovaquia', 'area' => '421'],
            ['nombre' => 'Eslovenia', 'area' => '386'],
            ['nombre' => 'España', 'area' => '34'],
            ['nombre' => 'Estados Unidos de América', 'area' => '1'],
            ['nombre' => 'Estonia', 'area' => '372'],
            ['nombre' => 'Etiopía', 'area' => '251'],
            ['nombre' => 'Filipinas', 'area' => '63'],
            ['nombre' => 'Finlandia', 'area' => '358'],
            ['nombre' => 'Fiyi', 'area' => '679'],
            ['nombre' => 'Francia', 'area' => '33'],
            ['nombre' => 'Gabón', 'area' => '241'],
            ['nombre' => 'Gambia', 'area' => '220'],
            ['nombre' => 'Georgia', 'area' => '995'],
            ['nombre' => 'Ghana', 'area' => '233'],
            ['nombre' => 'Gibraltar', 'area' => '350'],
            ['nombre' => 'Granada', 'area' => '1 473'],
            ['nombre' => 'Grecia', 'area' => '30'],
            ['nombre' => 'Groenlandia', 'area' => '299'],
            ['nombre' => 'Guadalupe', 'area' => '590'],
            ['nombre' => 'Guam', 'area' => '1 671'],
            ['nombre' => 'Guatemala', 'area' => '502'],
            ['nombre' => 'Guayana Francesa', 'area' => '594'],
            ['nombre' => 'Guernsey', 'area' => '44'],
            ['nombre' => 'Guinea', 'area' => '224'],
            ['nombre' => 'Guinea Ecuatorial', 'area' => '240'],
            ['nombre' => 'Guinea-Bissau', 'area' => '245'],
            ['nombre' => 'Guyana', 'area' => '592'],
            ['nombre' => 'Haití', 'area' => '509'],
            ['nombre' => 'Honduras', 'area' => '504'],
            ['nombre' => 'Hong kong', 'area' => '852'],
            ['nombre' => 'Hungría', 'area' => '36'],
            ['nombre' => 'India', 'area' => '91'],
            ['nombre' => 'Indonesia', 'area' => '62'],
            ['nombre' => 'Irán', 'area' => '98'],
            ['nombre' => 'Irak', 'area' => '964'],
            ['nombre' => 'Irlanda', 'area' => '353'],
            ['nombre' => 'Isla Bouvet', 'area' => ''],
            ['nombre' => 'Isla de Man', 'area' => '44'],
            ['nombre' => 'Isla de Navidad', 'area' => '61'],
            ['nombre' => 'Isla Norfolk', 'area' => '672'],
            ['nombre' => 'Islandia', 'area' => '354'],
            ['nombre' => 'Islas Bermudas', 'area' => '1 441'],
            ['nombre' => 'Islas Caimán', 'area' => '1 345'],
            ['nombre' => 'Islas Cocos (Keeling)', 'area' => '61'],
            ['nombre' => 'Islas Cook', 'area' => '682'],
            ['nombre' => 'Islas de Åland', 'area' => '358'],
            ['nombre' => 'Islas Feroe', 'area' => '298'],
            ['nombre' => 'Islas Georgias del Sur y Sandwich del Sur', 'area' => '500'],
            ['nombre' => 'Islas Heard y McDonald', 'area' => ''],
            ['nombre' => 'Islas Maldivas', 'area' => '960'],
            ['nombre' => 'Islas Malvinas', 'area' => '500'],
            ['nombre' => 'Islas Marianas del Norte', 'area' => '1 670'],
            ['nombre' => 'Islas Marshall', 'area' => '692'],
            ['nombre' => 'Islas Pitcairn', 'area' => '870'],
            ['nombre' => 'Islas Salomón', 'area' => '677'],
            ['nombre' => 'Islas Turcas y Caicos', 'area' => '1 649'],
            ['nombre' => 'Islas Ultramarinas Menores de Estados Unidos', 'area' => '246'],
            ['nombre' => 'Islas Vírgenes Británicas', 'area' => '1 284'],
            ['nombre' => 'Islas Vírgenes de los Estados Unidos', 'area' => '1 340'],
            ['nombre' => 'Israel', 'area' => '972'],
            ['nombre' => 'Italia', 'area' => '39'],
            ['nombre' => 'Jamaica', 'area' => '1 876'],
            ['nombre' => 'Japón', 'area' => '81'],
            ['nombre' => 'Jersey', 'area' => '44'],
            ['nombre' => 'Jordania', 'area' => '962'],
            ['nombre' => 'Kazajistán', 'area' => '7'],
            ['nombre' => 'Kenia', 'area' => '254'],
            ['nombre' => 'Kirguistán', 'area' => '996'],
            ['nombre' => 'Kiribati', 'area' => '686'],
            ['nombre' => 'Kuwait', 'area' => '965'],
            ['nombre' => 'Líbano', 'area' => '961'],
            ['nombre' => 'Laos', 'area' => '856'],
            ['nombre' => 'Lesoto', 'area' => '266'],
            ['nombre' => 'Letonia', 'area' => '371'],
            ['nombre' => 'Liberia', 'area' => '231'],
            ['nombre' => 'Libia', 'area' => '218'],
            ['nombre' => 'Liechtenstein', 'area' => '423'],
            ['nombre' => 'Lituania', 'area' => '370'],
            ['nombre' => 'Luxemburgo', 'area' => '352'],
            ['nombre' => 'México', 'area' => '52'],
            ['nombre' => 'Mónaco', 'area' => '377'],
            ['nombre' => 'Macao', 'area' => '853'],
            ['nombre' => 'Macedônia', 'area' => '389'],
            ['nombre' => 'Madagascar', 'area' => '261'],
            ['nombre' => 'Malasia', 'area' => '60'],
            ['nombre' => 'Malawi', 'area' => '265'],
            ['nombre' => 'Mali', 'area' => '223'],
            ['nombre' => 'Malta', 'area' => '356'],
            ['nombre' => 'Marruecos', 'area' => '212'],
            ['nombre' => 'Martinica', 'area' => '596'],
            ['nombre' => 'Mauricio', 'area' => '230'],
            ['nombre' => 'Mauritania', 'area' => '222'],
            ['nombre' => 'Mayotte', 'area' => '262'],
            ['nombre' => 'Micronesia', 'area' => '691'],
            ['nombre' => 'Moldavia', 'area' => '373'],
            ['nombre' => 'Mongolia', 'area' => '976'],
            ['nombre' => 'Montenegro', 'area' => '382'],
            ['nombre' => 'Montserrat', 'area' => '1 664'],
            ['nombre' => 'Mozambique', 'area' => '258'],
            ['nombre' => 'Namibia', 'area' => '264'],
            ['nombre' => 'Nauru', 'area' => '674'],
            ['nombre' => 'Nepal', 'area' => '977'],
            ['nombre' => 'Nicaragua', 'area' => '505'],
            ['nombre' => 'Niger', 'area' => '227'],
            ['nombre' => 'Nigeria', 'area' => '234'],
            ['nombre' => 'Niue', 'area' => '683'],
            ['nombre' => 'Noruega', 'area' => '47'],
            ['nombre' => 'Nueva Caledonia', 'area' => '687'],
            ['nombre' => 'Nueva Zelanda', 'area' => '64'],
            ['nombre' => 'Omán', 'area' => '968'],
            ['nombre' => 'Países Bajos', 'area' => '31'],
            ['nombre' => 'Pakistán', 'area' => '92'],
            ['nombre' => 'Palau', 'area' => '680'],
            ['nombre' => 'Palestina', 'area' => '970'],
            ['nombre' => 'Panamá', 'area' => '507'],
            ['nombre' => 'Papúa Nueva Guinea', 'area' => '675'],
            ['nombre' => 'Paraguay', 'area' => '595'],
            ['nombre' => 'Perú', 'area' => '51'],
            ['nombre' => 'Polinesia Francesa', 'area' => '689'],
            ['nombre' => 'Polonia', 'area' => '48'],
            ['nombre' => 'Portugal', 'area' => '351'],
            ['nombre' => 'Puerto Rico', 'area' => '1'],
            ['nombre' => 'Qatar', 'area' => '974'],
            ['nombre' => 'Reino Unido', 'area' => '44'],
            ['nombre' => 'República Centroafricana', 'area' => '236'],
            ['nombre' => 'República Checa', 'area' => '420'],
            ['nombre' => 'República Dominicana', 'area' => '1 809'],
            ['nombre' => 'República de Sudán del Sur', 'area' => '211'],
            ['nombre' => 'Reunión', 'area' => '262'],
            ['nombre' => 'Ruanda', 'area' => '250'],
            ['nombre' => 'Rumanía', 'area' => '40'],
            ['nombre' => 'Rusia', 'area' => '7'],
            ['nombre' => 'Sahara Occidental', 'area' => '212'],
            ['nombre' => 'Samoa', 'area' => '685'],
            ['nombre' => 'Samoa Americana', 'area' => '1 684'],
            ['nombre' => 'San Bartolomé', 'area' => '590'],
            ['nombre' => 'San Cristóbal y Nieves', 'area' => '1 869'],
            ['nombre' => 'San Marino', 'area' => '378'],
            ['nombre' => 'San Martín (Francia)', 'area' => '1 599'],
            ['nombre' => 'San Pedro y Miquelón', 'area' => '508'],
            ['nombre' => 'San Vicente y las Granadinas', 'area' => '1 784'],
            ['nombre' => 'Santa Elena', 'area' => '290'],
            ['nombre' => 'Santa Lucía', 'area' => '1 758'],
            ['nombre' => 'Santo Tomé y Príncipe', 'area' => '239'],
            ['nombre' => 'Senegal', 'area' => '221'],
            ['nombre' => 'Serbia', 'area' => '381'],
            ['nombre' => 'Seychelles', 'area' => '248'],
            ['nombre' => 'Sierra Leona', 'area' => '232'],
            ['nombre' => 'Singapur', 'area' => '65'],
            ['nombre' => 'Sint Maarten', 'area' => '1 721'],
            ['nombre' => 'Siria', 'area' => '963'],
            ['nombre' => 'Somalia', 'area' => '252'],
            ['nombre' => 'Sri lanka', 'area' => '94'],
            ['nombre' => 'Sudáfrica', 'area' => '27'],
            ['nombre' => 'Sudán', 'area' => '249'],
            ['nombre' => 'Suecia', 'area' => '46'],
            ['nombre' => 'Suiza', 'area' => '41'],
            ['nombre' => 'Surinám', 'area' => '597'],
            ['nombre' => 'Svalbard y Jan Mayen', 'area' => '47'],
            ['nombre' => 'Swazilandia', 'area' => '268'],
            ['nombre' => 'Tayikistán', 'area' => '992'],
            ['nombre' => 'Tailandia', 'area' => '66'],
            ['nombre' => 'Taiwán', 'area' => '886'],
            ['nombre' => 'Tanzania', 'area' => '255'],
            ['nombre' => 'Territorio Británico del Océano Índico', 'area' => '246'],
            ['nombre' => 'Territorios Australes y Antárticas Franceses', 'area' => ''],
            ['nombre' => 'Timor Oriental', 'area' => '670'],
            ['nombre' => 'Togo', 'area' => '228'],
            ['nombre' => 'Tokelau', 'area' => '690'],
            ['nombre' => 'Tonga', 'area' => '676'],
            ['nombre' => 'Trinidad y Tobago', 'area' => '1 868'],
            ['nombre' => 'Tunez', 'area' => '216'],
            ['nombre' => 'Turkmenistán', 'area' => '993'],
            ['nombre' => 'Turquía', 'area' => '90'],
            ['nombre' => 'Tuvalu', 'area' => '688'],
            ['nombre' => 'Ucrania', 'area' => '380'],
            ['nombre' => 'Uganda', 'area' => '256'],
            ['nombre' => 'Uruguay', 'area' => '598'],
            ['nombre' => 'Uzbekistán', 'area' => '998'],
            ['nombre' => 'Vanuatu', 'area' => '678'],
            ['nombre' => 'Venezuela', 'area' => '58'],
            ['nombre' => 'Vietnam', 'area' => '84'],
            ['nombre' => 'Wallis y Futuna', 'area' => '681'],
            ['nombre' => 'Yemen', 'area' => '967'],
            ['nombre' => 'Yibuti', 'area' => '253'],
            ['nombre' => 'Zambia', 'area' => '260'],
            ['nombre' => 'Zimbabue', 'area' => '263'],
        );
        foreach ($arrayData as $key => $value) {
            PaisModel::create([
                'nombre' => $value['nombre'],
                'area' => $value['area'],
            ]);
        }
    }
}
